version: '3'

services:
  ts-app:
    build:
      context: hellow/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HELLO_RESPONSE: "planet"

